[package]
name = "teashop"
version = "0.1.0"
edition = "2024"
authors = ["XoanOuteiro"]
description = "🫖 The Tea Docker flavor manager."
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dirs = "6.0.0"
colored = "3.0.0"
